### ISSUE TITLE
Error: statusCode 422

### ISSUE THREAD

**Issue by rafaelcmrj** [rferro/plnx#16]
It's returning `Error: statusCode 422` when I call any margin-related method, such as `getMarginPosition ` and `closeMarginPosition `.

`Error: statusCode 422
    at Request._callback (/Library/WebServer/Documents/cryptocurrencies/renko-tradingview-bot/node_modules/plnx/lib/index.js:144:12)
    at Request.self.callback (/Library/WebServer/Documents/cryptocurrencies/renko-tradingview-bot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Library/WebServer/Documents/cryptocurrencies/renko-tradingview-bot/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Library/WebServer/Documents/cryptocurrencies/renko-tradingview-bot/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)`

**Comment by rafaelcmrj** [comment]
currencyPair was wrong
